### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ghost** [deptyped/telegraf-callback-data#8]
![image](https://user-images.githubusercontent.com/73015901/125182680-c0ff9580-e218-11eb-9262-7b08f649c608.png)

**Comment by ghost** [comment]
answer:  try`"skipLibCheck": true` in tsconfig.json and off "strict".

**Comment by deptyped** [comment]
Fixed in 0.2.4 🎉

**Comment by neoantox** [comment]
@deptyped I still get the error on version 0.2.4:

![image](https://user-images.githubusercontent.com/134825/149474049-a1466e0d-3cb1-4a5b-8b4a-1dfc7a8c9916.png)

Workaround: `"strict": false` in tsconfig.json

**Comment by deptyped** [comment]
@neoantox 
Thanks for the report! Can you reproduce this problem in 0.2.6?
